// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC8LX-1erjqbNGzGyX7rAzXkWv9QSKr3g',
    appId: '1:641852285608:web:5a2da8299eddea7950189d',
    messagingSenderId: '641852285608',
    projectId: 'stocklio-playground',
    authDomain: 'stocklio-playground.firebaseapp.com',
    databaseURL: 'https://stocklio-playground-default-rtdb.firebaseio.com',
    storageBucket: 'stocklio-playground.appspot.com',
    measurementId: 'G-XBJ31LR1E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6tnyH2RyEoBoArScv2wHr5hYSbjVKTQ',
    appId: '1:641852285608:android:27a2c05f602b7ec950189d',
    messagingSenderId: '641852285608',
    projectId: 'stocklio-playground',
    databaseURL: 'https://stocklio-playground-default-rtdb.firebaseio.com',
    storageBucket: 'stocklio-playground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBScJ4gJBElyGBp8ouo8EDDImNtjltwuX4',
    appId: '1:641852285608:ios:78089ea6fd11f4bc50189d',
    messagingSenderId: '641852285608',
    projectId: 'stocklio-playground',
    databaseURL: 'https://stocklio-playground-default-rtdb.firebaseio.com',
    storageBucket: 'stocklio-playground.appspot.com',
    iosClientId:
        '641852285608-90c8v4noi8dilj64ipk5c1k958g8cqtr.apps.googleusercontent.com',
    iosBundleId: 'io.stockl.stocklio',
  );
}
